### ISSUE TITLE
[Compatibility] Add compatibility for Mythic Metals Decorations

### ISSUE THREAD

**Issue by Zunwolf1896** [Infinituum17/LabellingContainers#5]
Mythic Metals Decorations adds a lot of new chest types, would be nice for the label to work on them

**Comment by Infinituum17** [comment]
I'll add it as soon as possible. Thanks for the suggestion!

**Comment by Infinituum17** [comment]
Done! I've added compatibility with Mythic Metals Decorations in 1.19.2, 1.19.3, 1.19.4 and 1.20

**Comment by Infinituum17** [comment]
Yep sure, my bad. I tought Mythic Metals Decorations were available only in version 1.20 because on curseforge there wasn't an explicit tag posted with the latest version. In fact you can't even download that mod for mc1.20.1 using the curseforge launcher, but I've tested it locally and it seems to work fine.

I'll release a new version just for 1.20.1 and 1.20.2 that adds compatibility between the two mods.

**Comment by Infinituum17** [comment]
Here is 1.20.1 version: [Download on Modrinth](https://modrinth.com/mod/labelling-containers/version/1.3.1) | [Download on CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/labelling-containers/files/4927763).

Small side note: I can't update to 1.20.2 because Mythic Metals hasn't been updated yet.

**Comment by Zunwolf1896** [comment]
Hey, back again. This still does not seem to be compatible. 

We are using (will be releasing a modpack update in 7 days)
Labellingcontainers 1.5.1 
Mythic metals 0.19.3
Mytich Upgrades 2.4.2

We clickign on a mythic chest wiht teh label, it gives the noise, and when clickign again it gives the particles. But it does not apply to the chests.

**Comment by Infinituum17** [comment]
What version of Minecraft are you using?

**Comment by Infinituum17** [comment]
I can't reproduce this bug, for me it works fine (I tested it both in my development environment and on CurseForge).

![image](https://github.com/Infinituum17/LabellingContainers/assets/40234342/eaba3dc4-89d0-4643-ad63-e67872c6d318)
![image](https://github.com/Infinituum17/LabellingContainers/assets/40234342/9cf8066f-c295-418a-b38f-cfea4d26b594)

It could be a problem caused by another mod you installed, and also, just to check, what version of Minecraft are you using?

Have you tried changing world? Maybe you used an older version in that world and now for some reason it is bugged.

If you want me to check what the problem could be, follow this steps:
1. Start up Minecraft like usual, open your world, do the thing again on a new chest.
2. Save and exit, open your installation folder, find the `latest.log` file (logs directory) and send it to me (here or on Discord, my nickname is "infinituum").
